# Generated by Django 3.1.2 on 2020-10-13 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_description', models.TextField()),
                ('product_photo', models.ImageField(upload_to='')),
                ('max_numbers', models.PositiveSmallIntegerField(default=25)),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('telegram_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_numbers', to='sorteo_api.raffle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='sorteo_api.user')),
            ],
        ),
    ]
