# Generated by Django 3.1.2 on 2020-10-13 19:09

from django.db import migrations


def set_initial_users(apps, schema_editor):
    User = apps.get_model('sorteo_api', 'User')
    users_data = [
        { 'telegram_id':641219615, 'is_admin':True, 'is_blocked':False },
        { 'telegram_id':827195251, 'is_admin':True, 'is_blocked':False },
    ]
    users = [User(**user) for user in users_data]
    User.objects.bulk_create(users)


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_initial_users)
    ]
